/**
 * Writes .env for local Cloth testing.
 * Prefers URLs from `supabase status -o env` when local Supabase is running;
 * otherwise copies placeholders from .env.example and fills AUTH/CRON secrets.
 */
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const envPath = resolve(root, ".env");
const examplePath = resolve(root, ".env.example");

function parseEnv(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function formatEnv(vars) {
  const lines = [
    "# Generated by npm run setup — do not commit",
    "",
    `DATABASE_URL="${vars.DATABASE_URL}"`,
    `DIRECT_URL="${vars.DIRECT_URL}"`,
    "",
    `AUTH_SECRET="${vars.AUTH_SECRET}"`,
    `AUTH_URL="${vars.AUTH_URL}"`,
    `CRON_SECRET="${vars.CRON_SECRET}"`,
    "",
  ];
  return lines.join("\n");
}

function trySupabaseEnv() {
  try {
    const raw = execSync("npx supabase status -o env", {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return parseEnv(raw);
  } catch {
    return null;
  }
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {};
const example = existsSync(examplePath)
  ? parseEnv(readFileSync(examplePath, "utf8"))
  : {};
const supabase = trySupabaseEnv();

const databaseUrl =
  supabase?.DATABASE_URL ||
  existing.DATABASE_URL ||
  example.DATABASE_URL ||
  "";
const directUrl =
  supabase?.DIRECT_URL ||
  existing.DIRECT_URL ||
  databaseUrl.replace(":6543", ":5432").replace("?pgbouncer=true", "") ||
  example.DIRECT_URL ||
  "";

// Local supabase status usually exposes DB URL as DATABASE_URL (direct :5432).
// For Prisma we can use the same local URL for both when not using a pooler.
const localDb =
  supabase?.DB_URL ||
  supabase?.POSTGRES_URL ||
  supabase?.DATABASE_URL ||
  null;

const vars = {
  DATABASE_URL: localDb || databaseUrl,
  DIRECT_URL: localDb || directUrl,
  AUTH_SECRET:
    existing.AUTH_SECRET || randomBytes(32).toString("hex"),
  AUTH_URL: existing.AUTH_URL || "http://localhost:3000",
  CRON_SECRET:
    existing.CRON_SECRET || randomBytes(16).toString("hex"),
};

const looksPlaceholder =
  !vars.DATABASE_URL ||
  vars.DATABASE_URL.includes("[PROJECT-REF]") ||
  vars.DATABASE_URL.includes("[PASSWORD]") ||
  vars.DATABASE_URL.includes("[POOLER-HOST]");

writeFileSync(envPath, formatEnv(vars), "utf8");

if (looksPlaceholder) {
  console.log("Wrote .env with AUTH secrets, but DATABASE_URL still needs a real Postgres URL.");
  console.log("");
  console.log("Option 1 — local Supabase (Docker Desktop must be running):");
  console.log("  npx supabase start");
  console.log("  npm run setup");
  console.log("");
  console.log("Option 2 — hosted Supabase:");
  console.log("  Dashboard → Connect → copy pooler + direct URLs into .env");
  console.log("  (see .env.example)");
  console.log("");
  process.exitCode = 1;
} else {
  console.log("Wrote .env with Supabase Postgres URLs and auth secrets.");
  console.log("Next: npm run db:push && npm run dev");
}
